use std::fs;
use std::path::Path;

fn main() {
    let languages_json =
        fs::read_to_string("../languages.json").expect("Failed to read languages.json");
    let languages: Vec<String> =
        serde_json::from_str(&languages_json).expect("Failed to parse languages.json");

    let mut content = String::from("// This file is auto-generated by build.rs\n");
    content.push_str("// Do not modify this file manually.\n\n");
    content.push_str("pub const SUPPORTED_LANGUAGES: &[&str] = &[\n");
    for lang in &languages {
        content.push_str(&format!("    \"{}\",\n", lang));
    }
    content.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("languages.rs");
    fs::write(&dest_path, content).expect("Failed to write languages.rs");

    tauri_build::build()
}
