use std::fs;
use std::path::Path;

fn main() {
    let languages_json =
        fs::read_to_string("../languages.json").expect("Failed to read languages.json");
    let languages: Vec<String> =
        serde_json::from_str(&languages_json).expect("Failed to parse languages.json");

    let mut content = String::from("// This file is auto-generated by build.rs\n");
    content.push_str("// Do not modify this file manually.\n\n");
    content.push_str(
        "#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Copy, PartialEq, Eq)]\n",
    );
    content.push_str("pub enum Language {\n");
    for lang in &languages {
        let variant_name = format!(
            "{}{}",
            lang.chars()
                .next()
                .unwrap()
                .to_uppercase()
                .collect::<String>(),
            &lang[1..]
        );
        content.push_str(&format!("    #[serde(rename = \"{}\")]\n", lang));
        content.push_str(&format!("    {},\n", variant_name));
    }
    content.push_str("}\n\n");
    content.push_str("impl Default for Language {\n");
    content.push_str("    fn default() -> Self {\n");
    content.push_str(&format!(
        "        Self::{}{}",
        languages[0]
            .chars()
            .next()
            .unwrap()
            .to_uppercase()
            .collect::<String>(),
        &languages[0][1..]
    ));
    content.push_str("\n");
    content.push_str("    }\n");
    content.push_str("}\n");

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("languages.rs");
    fs::write(&dest_path, content).expect("Failed to write languages.rs");

    tauri_build::build()
}
