import fs from "fs";
import path from "path";

const languagesPath = path.resolve("languages.json");
const outputPath = path.resolve("src/lib/languages.ts");

const languages = JSON.parse(fs.readFileSync(languagesPath, "utf-8"));

const content = `// This file is auto-generated by scripts/sync-locales.js
// Do not modify this file manually.

export const languages = ${JSON.stringify(languages)} as const;
export type Locale = (typeof languages)[number];
`;

fs.writeFileSync(outputPath, content);
console.debug(`Generated ${outputPath}`);
